-- MySQL Script generated by MySQL Workbench
-- mar. 05 déc. 2023 17:05:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Blogs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Blogs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Blogs` (
  `idBlog` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(85) NOT NULL,
  `Description` LONGTEXT NULL,
  `Date_creation` DATE NOT NULL,
  `Visible` TINYINT NOT NULL DEFAULT 1,
  `Background_color` VARCHAR(45) NULL,
  `Background_image` VARCHAR(255) NULL,
  `Typo_title` VARCHAR(45) NULL,
  `Typo_text` VARCHAR(45) NULL,
  `idUsers` INT NOT NULL,
  PRIMARY KEY (`idBlog`),
  INDEX `Fk_Blog_idx` (`idUsers` ASC) VISIBLE,
  CONSTRAINT `Fk_Blog`
    FOREIGN KEY (`idUsers`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(85) NOT NULL,
  `Email` VARCHAR(85) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Picture` VARCHAR(255) NULL,
  `Role` VARCHAR(45) NOT NULL DEFAULT 'User',
  PRIMARY KEY (`idUsers`),
  UNIQUE INDEX `idUsers_UNIQUE` (`idUsers` ASC) VISIBLE,
  CONSTRAINT `fk_Users_1`
    FOREIGN KEY (`idUsers`)
    REFERENCES `mydb`.`Blogs` (`idBlog`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tags` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tags` (
  `idTag` INT NOT NULL AUTO_INCREMENT,
  `Tag_Name` VARCHAR(85) NOT NULL,
  `idUsers` INT NOT NULL,
  PRIMARY KEY (`idTag`),
  UNIQUE INDEX `idTag_UNIQUE` (`idTag` ASC) VISIBLE,
  INDEX `fk_Tag_user_idx` (`idUsers` ASC) VISIBLE,
  CONSTRAINT `fk_Tag_user`
    FOREIGN KEY (`idUsers`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Articles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Articles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Articles` (
  `idArticle` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(255) NOT NULL,
  `Image` VARCHAR(255) NULL,
  `Content` LONGTEXT NULL,
  `Date` DATE NOT NULL,
  `Visible` TINYINT NOT NULL DEFAULT 1,
  `idBlog` INT NOT NULL,
  `idTag` INT NOT NULL,
  PRIMARY KEY (`idArticle`),
  UNIQUE INDEX `idArticles_UNIQUE` (`idArticle` ASC) VISIBLE,
  INDEX `fk_Articles_2_idx` (`idBlog` ASC) VISIBLE,
  INDEX `fk_Articles_tag_idx` (`idTag` ASC) VISIBLE,
  CONSTRAINT `fk_Article_blog`
    FOREIGN KEY (`idBlog`)
    REFERENCES `mydb`.`Blogs` (`idBlog`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articles_tag`
    FOREIGN KEY (`idTag`)
    REFERENCES `mydb`.`Tags` (`idTag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Comments` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Comments` (
  `idComment` INT NOT NULL AUTO_INCREMENT,
  `Content` LONGTEXT NOT NULL,
  `Date` DATETIME NOT NULL,
  `Update` TINYINT NOT NULL DEFAULT 0,
  `Update_date` DATETIME NULL,
  `Visible` TINYINT NOT NULL DEFAULT 1,
  `idUsers` INT NOT NULL,
  `idArticle` INT NOT NULL,
  PRIMARY KEY (`idComment`),
  UNIQUE INDEX `idComment_UNIQUE` (`idComment` ASC) VISIBLE,
  INDEX `fk_Comments_1_idx` (`idUsers` ASC) VISIBLE,
  INDEX `fk_Comments_2_idx` (`idArticle` ASC) VISIBLE,
  CONSTRAINT `fk_Comment_user`
    FOREIGN KEY (`idUsers`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_article`
    FOREIGN KEY (`idArticle`)
    REFERENCES `mydb`.`Articles` (`idArticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
